### ISSUE TITLE
About bn_update

### ISSUE THREAD

**Issue by zllrunning** [tugstugi/pytorch-saltnet#4]
Hi, @tugstugi 
I know we should run one additional pass over the training data to get the running mean and running var. But why change momentum?
```
        momentum = b / (n + b)
        for module in momenta.keys():
            module.momentum = momentum
```

**Comment by xuyuan** [comment]
I think it computes mean and var instead of running mean and running var.

**Comment by zllrunning** [comment]
OK，but do you know why change momentum?
